name: Docker image
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main
      - 'v*.*'
      - '*'

jobs:
  build:
    name: Build & push docker image
    runs-on: mend-new-runer-1-label-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: mend-white-src-scan
      
      - name: Present working directory        
        run: pwd

      - name: Check PR Description for Flags
        id: check-flags
        run: |
          PR_BODY=$(jq -r .pull_request.body "$GITHUB_EVENT_PATH")
          echo "PR Body: $PR_BODY"
          if echo "$PR_BODY" | grep -q "Run Whitesource scan"; then
            echo "::set-output name=flag_a::true"
          fi

      - name: Convert HTML to Markdown and Comment added
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Ensure gh CLI is installed and authenticated
          echo "Checking GitHub CLI installation..."
          gh --version

          # Read the HTML content
          if [ -f /home/itadmin/ws_report/whitesource_scan_urls.html ]; then
           HTML_CONTENT=$(cat /home/itadmin/ws_report/whitesource_scan_urls.html)

           # Check if there's an existing comment by the same author
           echo "Checking for existing comments by the same author..."
           COMMENTS=$(gh pr view ${{ github.event.pull_request.number }} --json comments --jq ".comments[].author.login")

           if echo "$COMMENTS" | grep -q "$(gh api user | jq -r .login)"; then
            # Update the last comment
            echo "Updating the last comment by the same author..."
            gh pr comment ${{ github.event.pull_request.number }} --edit-last --body "$HTML_CONTENT"
           else
            # Create a new comment
            echo "Creating a new comment..."
            gh pr comment ${{ github.event.pull_request.number }} --body "$HTML_CONTENT"
           fi
          else
           echo "HTML file not found."
          fi


      - name: Run Whitesource scan is Checked
        if: steps.check-flags.outputs.flag_a == 'true'
        run: echo "Running Whitesource scan"
      
      - name: List Docker images with 'latest' tag
        id: list-images
        run: |
          IMAGES=$(docker images --format "{{.Repository}}:latest" | sort | uniq)
          if [ -z "$IMAGES" ]; then
            echo "No Docker images with 'latest' tag found."
            exit 1
          else
            echo "Docker images with 'latest' tag found:"
            echo "$IMAGES"
          fi        

      - name: Tag Docker images with "GHA"
        run: |
          IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep ':latest' | sort | uniq)       
          for IMAGE in $IMAGES; do
            echo "Inside for loop...IMAGE==="
            echo $IMAGE
            echo "docker tag $IMAGE ${IMAGE%:latest}:GHA"            
            docker tag $IMAGE ${IMAGE%:latest}:GHA
            docker rmi $IMAGE            
          done
