name: Docker image
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  build:
    name: Build & push docker image
    runs-on: mend-new-runer-1-label-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: |
            mend-white-src-scan
            ${{ github.event.pull_request.head.ref }} 
      
      - name: Present working directory        
        run: pwd

      - name: Check PR Description for Flags
        id: check-flags
        if: github.event_name == 'pull_request'
        run: |
          PR_BODY=$(jq -r .pull_request.body "$GITHUB_EVENT_PATH")
          echo "PR Body: $PR_BODY"
          if echo "$PR_BODY" | grep -q "Run Whitesource scan"; then
            echo "flag_a=true" >> $GITHUB_ENV
          fi

      - name: Debug Event Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Branch: ${{ github.ref }}"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "PR Base Ref: ${{ github.event.pull_request.base.ref }}"
            echo "PR Head Ref: ${{ github.event.pull_request.head.ref }}"
          else
            echo "This is not a pull request event."
          fi
    
      - name: Get Pull Request Number
        id: pr
        if: github.event_name == 'pull_request'
        run: |
          PR_NUMBER=$(gh pr view --json number -q .number)
          echo "Pull Request Number: $PR_NUMBER"
          echo "pull_request_number=$PR_NUMBER" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Find Whitesource Log Directory
        id: find-log-dir
        run: |
          LOG_DIR=$(ls -td /home/itadmin/mend-runner/bigfix-docker/whitesource/*/ | head -n 1)
          echo "Log directory found: $LOG_DIR"
          echo "log_dir=$LOG_DIR" >> $GITHUB_ENV
          
      - name: Make utility.sh Executable
        run: chmod +x /home/itadmin/mend-runner/actions-runner/_work/springboot-starterkit/springboot-starterkit/.github/utils/scripts/utility.sh
          
      - name: Run Utility Script with Whitesource Log
        run: |
          LOG_FILE="${{ env.log_dir }}whitesource.0.log"
          sh /home/itadmin/mend-runner/actions-runner/_work/springboot-starterkit/springboot-starterkit/.github/utils/scripts/utility.sh "$LOG_FILE"
          
      - name: Publish whitesource report to PR page
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Checking GitHub CLI installation..."
          gh --version

          PR_NUMBER=${{ env.pull_request_number }}
          echo "Pull Request Number: $PR_NUMBER"

          if [ -f /home/itadmin/ws_report/whitesource_scan_urls.md ]; then
            echo "Markdown file found. Reading content..."
            MD_CONTENT=$(cat /home/itadmin/ws_report/whitesource_scan_urls.md)
            
            echo "Markdown content:"
            echo "$MD_CONTENT"

            COMMENTS=$(gh pr view $PR_NUMBER --json comments --jq ".comments[].author.login")
            CURRENT_USER=$(gh api user | jq -r .login)

            if echo "$COMMENTS" | grep -q "$CURRENT_USER"; then
              echo "Updating the last comment by the same author..."
              gh pr comment $PR_NUMBER --edit-last --body "$MD_CONTENT"
            else
              echo "Creating a new comment..."
              gh pr comment $PR_NUMBER --body "$MD_CONTENT"
            fi
          else
            echo "Markdown file not found."
          fi
