name: Docker image
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main
      - 'v*.*'
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14 # or any image that includes the required versions
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Additional steps here
