name: Docker image
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main
      - 'v*.*'
      - '*'
jobs:
  build:
    name: Build & push docker image
    runs-on: mend-white-src-scan-runner-label-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: mend-white-src-scan

      